### ISSUE TITLE
Weird Crash

### ISSUE THREAD

**Issue by CoolGuyGit** [TheOnlySD12/SoundBoard#1]
I recently discovered your mod and whenever I tried to use it in game, it crashed even with nothing but it and the fabric API.  Im not sure why it is crashing specifically but it happens every time I try to open the soundboard menu with 'O'.  Here is my crash report.  
[crash-2023-08-08_18.45.50-client.txt](https://github.com/TheOnlySD12/SoundBoard/files/12296880/crash-2023-08-08_18.45.50-client.txt)

**Comment by TheOnlySD12** [comment]
Hi, thanks for reporting this issue. I have fixed it in [the latest version](https://modrinth.com/mod/soundboard/version/2.5.2).
